name: "Deploy with Bacon"
description: "Deploy DNS records with Bacon"
inputs:
  config:
    description: "Config file to deploy"
    required: true
  delete:
    description: "Delete outdated records"
    required: false
  create:
    description: "Create new records"
    required: false
runs:
  using: "composite"
  steps:
    - name: Checkout workspace
      uses: actions/checkout@v3
      with:
        path: workspace

    # Clone and build Bacon
    - name: Install Go
      uses: actions/setup-go@v3
      with:
        go-version: "1.18"
    - name: Clone bacon
      shell: bash
      run: git clone https://github.com/jungaretti/bacon.git bacon
    - name: Build bacon
      shell: bash
      working-directory: bacon
      run: go build -o bin/bacon .

    # Ping and deploy the config file
    - name: Ping test
      shell: bash
      run: bacon/bin/bacon ping
    - name: Deploy config
      shell: bash
      run: |
        [ ${{ inputs.delete }} = 'true' ] && DELETE='-c' || DELETE=''
        [ ${{ inputs.create }} = 'true' ] && CREATE='-c' || CREATE=''
        bacon/bin/bacon deploy workspace/${{ inputs.config }} $DELETE $CREATE
