name: "Deploy with Bacon"
description: "Deploy DNS records with Bacon"
inputs:
  api-key:
    description: "Porkbun API key"
    required: true
  secret-key:
    description: "Porkbun secret key"
    required: true
  config:
    description: "Config file to deploy"
    required: true
  create:
    description: "Create new records"
    required: false
  delete:
    description: "Delete outdated records"
    required: false
runs:
  using: "composite"
  steps:
    - uses: pozetroninc/github-action-get-latest-release@v0.5.0
      id: get-bacon-release
      name: Fetch Bacon version
      with:
        owner: jungaretti
        repo: bacon
        excludes: prerelease, draft
    - name: Download Bacon
      shell: bash
      run: |
        VERSION=${{ steps.get-bacon-release.outputs.release }}
        ASSET="bacon-$VERSION-linux-amd64.tar.gz"
        URL="https://github.com/jungaretti/bacon/releases/download/$VERSION/$ASSET"

        # Download Bacon
        pushd "$(mktemp -d)"
        wget $URL -O $ASSET
        tar -xf $ASSET
        echo "::set-output name=bacon_bin::$(pwd)/bacon"
    - name: Deploy records
      shell: bash
      env:
        BACON_BIN: ${{ steps.clone-bacon.outputs.bacon_bin }}
        PORKBUN_API_KEY: ${{ inputs.api-key }}
        PORKBUN_SECRET_KEY: ${{ inputs.secret-key }}
      run: |
        [ "${{ inputs.delete }}" = 'true' ] && DELETE='-d' || DELETE=''
        [ "${{ inputs.create }}" = 'true' ] && CREATE='-c' || CREATE=''
        $BACON_BIN ping && $BACON_BIN deploy ${{ inputs.config }} $DELETE $CREATE
