name: "Deploy with Bacon"
description: "Deploy DNS records with Bacon"
inputs:
  config:
    description: "Config file to deploy"
    required: true
  delete:
    description: "Delete outdated records"
    default: false
  create:
    description: "Create new records"
    default: false
runs:
  using: "composite"
  steps:
    - name: Checkout workspace
      uses: actions/checkout@v3
      with:
        path: workspace
    - name: Checkout Bacon
      uses: actions/checkout@v3
      with:
        repo: jungaretti/bacon
        path: bacon
    
    - uses: actions/setup-go@v3
      with:
        go-version: "1.18"
    - name: Build Bacon
      working-directory: bacon
      run: go build -o bin/bacon .

    - name: Ping
      run: bacon/bin/bacon ping
    - name: Deploy
      run: |
        [ ${{ inputs.delete }} = 'true' ] && DELETE='-c' || DELETE=''
        [ ${{ inputs.create }} = 'true' ] && CREATE='-c' || CREATE=''
        bacon/bin/bacon deploy workspace/${{ inputs.config }} $DELETE $CREATE
